<?php  /* GENERATED AUTOMATICALLY AT 2011-10-03, DO NOT MODIFY */
class LibMap{
public static $map = 
array (
  '/' => 'main',
  'register' => 'register',
  'emailconfirm/%d/%s' => 'emailconfirm',
  'backend/*' => 'backend',
  404 => 'p404',
  'user/%d' => 'user',
  502 => 'p502',
  'book/%d' => 'book',
  'me' => 'me',
  'user/%d/edit' => 'useredit',
  'user/%d/books' => 'user_shelves',
  'user/%d/books/%s' => 'user_shelf',
  'author/%d' => 'author',
  'new' => 'books_new',
  'popular' => 'book_popular',
  'user/%d/friends' => 'user_friends',
  'user/%d/followers' => 'user_followers',
  'book/%d/edit' => 'book_edit',
  'genres/%s' => 'genre',
  'author/%d/edit' => 'author_edit',
  'book/new' => 'book_new',
  'author/new' => 'author_new',
  'a/%d/bibliography' => 'author_bibliography',
  'me/wall' => 'me_wall',
  'series' => 'series',
  'series/%d' => 'series_item',
  'm' => 'magazines',
  'm/%d' => 'magazine',
  'user/%d/wall' => 'wall',
  'forum' => 'forum',
  'series/%d/edit' => 'series_edit',
  'genres' => 'genres',
  'user/%d/reviews' => 'user_reviews',
  'forum/%d' => 'forum_themes',
  'forum/%d/%d' => 'forum_theme',
  'me/messages' => 'messages',
  'me/messages/%d' => 'messages_thread',
  'book/%d/log' => 'booklog',
  'author/%d/log' => 'authorlog',
  'user/%d/log' => 'userlog',
  'log' => 'log',
  'user/%d/wall/%s' => 'waal_post',
  'tracker' => 'tracker',
  'magazine/%d/edit' => 'magazine_edit',
);
public static $sinonim = 
array (
  'b/%d' => 'book/%d',
  'b/%d/edit' => 'book/%d/edit',
  'a/%d/edit' => 'author/%d/edit',
  'a/new' => 'author/new',
  'b/new' => 'book/new',
  'a/%d' => 'author/%d',
  's/%d' => 'series/%d',
  'magazines' => 'm',
  'magazine/%d' => 'm/%d',
  's/%d/edit' => 'series/%d/edit',
);
}